PROJECT=prezentace
TEX=pdflatex

all:
	$(TEX) $(PROJECT).tex

clean:
	rm -f *.toc *.aux *.log *.ilg *.lof *.lot *.out *.nav *.snm

cleanall:
	rm -f *.toc *.aux *.log *.ilg *.lof *.lot *.out *.nav *.snm *.pdf
